runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  script: static

- url: /.*
  script: main.app

- url: /js
  script: js



libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
